Update use of deprecated methods
LabKey/DiscvrLabKeyModules pull request #218
Opened 2023-04-06 22:50 UTC by labkey-matthewb

#### Rationale
append(Object) -> appendValue(), etc.
refactor SqlDialect.getGroupConcat()

#### Related Pull Requests
* 

#### Changes
*

2023-04-07 19:00 UTC, labkey-adam approved these changes

2023-04-07 19:01 UTC, labkey-adam requested changes
Tests are failing with assertion errors

2023-04-07 21:54 UTC, labkey-matthewb commented
> Tests are failing with assertion errors

Looks like that didn't rerun after https://github.com/LabKey/platform/commit/fab053c2c2e630dc117f93c47c904e8dd805a297

I'll launch manually

2023-04-07 22:20 UTC, labkey-matthewb commented
> > Tests are failing with assertion errors
> 
> Looks like that didn't rerun after [LabKey/platform@fab053c](https://github.com/LabKey/platform/commit/fab053c2c2e630dc117f93c47c904e8dd805a297)
> 
> I'll launch manually

I think I had relaunched the individual tests, but not the suite.

2023-04-08 04:36 UTC, labkey-adam approved these changes

2023-04-08 16:53 UTC, merged