Merge from onprc19.1 & onprc19.1Prod r.63271 to 65949
LabKey/DiscvrLabKeyModules pull request #64
Opened 2020-10-12 18:32 UTC by labkey-bpatel

#### Rationale
Merge changes from onprc19.1 r.63271 to 65757
Merge changes from onprc19.1Prod r. 65762 to 65949

#### Related Pull Requests
*

2020-10-12 23:41 UTC, labkey-jeckels approved these changes

2020-10-13 15:30 UTC, bbimber requested changes

2020-10-13 15:30 UTC, bbimber commented on SequenceAnalysis/src/org/labkey/sequenceanalysis/pipeline/IlluminaImportTask.java
> +                    if (rd.getFileId1() == null)
Do you have any info on why this needed?

2020-10-28 01:53 UTC, labkey-jeckels commented on SequenceAnalysis/src/org/labkey/sequenceanalysis/pipeline/IlluminaImportTask.java
> +                    if (rd.getFileId1() == null)
I tracked it down to revision 44984 in the onprc15.2 branch in March 2017. It was committed by Raymond with the comment "support for genetic ancestry data.  Author: B.Bimber"

It looks like it got dropped somewhere in a discvrX branch before being merged into trunk. I'll roll it back.

2020-10-28 12:14 UTC, bbimber approved these changes
this seems ok

2020-10-30 17:39 UTC, merged